### ISSUE TITLE
wish: support uploading only a specific S3 bucket + folder to the SFTP server

### ISSUE THREAD

**Issue by markstos** [renanivo/lambda-s3-sftp#1]

**Comment by renanivo** [comment]
I think it is currently supported by AWS. When you configure the lambda trigger on S3, you can specify "prefix", "filter pattern" and "bucket". 

<img width="1071" alt="lambda_management_console" src="https://user-images.githubusercontent.com/136425/37928865-af3b5c20-3114-11e8-92ec-37903906e348.png">

I'm closing this issue for the time beeing, but feel free to keep commenting on it. I'm open to reopen it if that's not what you need.

**Comment by markstos** [comment]
Thank you! That screenshot and detail could be helpful to include in the docs. Others may have the same interest.

**Comment by renanivo** [comment]
Good idea!
